<?php

use Drupal\Component\Utility\UrlHelper;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;
use Drupal\view_count\GetViewDataService;

/**
 * @param array $build
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 * @param $view_mode
 */
function view_count_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode === 'full') {
    $nid = \Drupal::routeMatch()->getRawParameter('node');

    // Get data for report on node.
    $view_results = \Drupal::service('view_count.get_view_data_service');
    $last_view = $view_results->getLastViewData($nid);
    $all_views = $view_results->getAllViewData($nid);
    $today_views = $view_results->getTodayViewData($nid);

    // Insert data into db, if not anonymous user.
    if (!\Drupal::currentUser()->isAnonymous()) {
      $uid = \Drupal::currentUser()->id();
      $view_results->setViewData($nid, $uid);
    }

    // Gather data for report on node page.
    $user_name = User::load($last_view['uid'])->getUsername();
    $access_time = date('m-d-Y', $last_view['timestamp']);

    // Add fields to node page.
    $build['all_views'] = [
      '#type'   => 'markup',
      '#markup' => t('Number of views: @today_views today / @all_views total',
        array('@today_views' => $today_views, '@all_views' => $all_views)),
      '#weight' => -2,
    ];
    $build['last_view'] = [
      '#type'   => 'markup',
      '#markup' => t('Last viewed by: @user_name at @access_time',
        array('@user_name' => $user_name, '@access_time' => $access_time)),
      '#weight' => -1,
    ];

    // Disable caching for.
    $build['#cache']['max-age'] = 0;
  }
}
