<?php

use Drupal\Component\Utility\UrlHelper;
use Drupal\node\Entity\Node;
use Drupal\view_count\GetViewDataService;

function view_count_node_view(
  array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode === 'full') {

    // Get data view count report input.
    $nid = \Drupal::routeMatch()->getRawParameter('node');

    $view_results = new GetViewDataService;
    $last_view = $view_results->getLastViewData($nid);
    $all_views = $view_results->getAllViewData($nid);
    $today_views = $view_results->getTodayViewData($nid);
    $view_results->setViewData($nid);

    // Gather data for report on node page.
    $user_name = User::load($last_view['uid'])->getUsername();
    $access_time = date('m-d-Y', $last_view['timestamp']);

    // Add fields to node page.
    $build['all_views'] = [
      '#type'   => 'markup',
      '#markup' => t('Number of views: @today_views today / @all_views total',
        array('@today_views' => $today_views, '@all_views' => $all_views)),
      '#weight' => -2,
    ];
    $build['last_view'] = [
      '#type'   => 'markup',
      '#markup' => t('Last viewed by: @user_name at @access_time',
        array('@user_name' => $user_name, '@access_time' => $access_time)),
      '#weight' => -1,
    ];
  }
}
